In [33]:
import numpy as np
import cv2

In [81]:
sideLen = 512 #圖片邊長
grayScale = 0 #黑色為初始值，255為白色
sideCounts = 2 #多少count後灰階值要加一
count = 0
img = np.zeros([sideLen, sideLen], dtype = 'uint8')

In [125]:
def diagonal_left(matrix):
    count = 0
    grayScale = 0 #黑色為初始值，255為白色
    sideCounts = 4 #多少count後灰階值要加一(一邊兩倍，兩邊四倍)
    row = len(matrix)
    col = len(matrix[0])
    k=0
    result = []
    for i in range(row):
        for j in range(k,col):  # j順序遍歷
            if(count == sideCounts):
                count = 0
                grayScale = grayScale + 1
            lst = []
            i1, j1 = i, j  # i1,j1用於方便同一對角線元素的新增，否則改變i,j影響開頭元素的選擇
            while i1 <= row - 1 and j1 >=0:
                lst.append(matrix[i1][j1])
                matrix[i1][j1] = grayScale
                j1 -= 1
                i1 += 1
            if i==0 and j==col-1:
                k=col-1
            count = count + 1
            result.append(lst)
    return ('the result is: %s' % result)

In [126]:
diagonal_left(img)
print(img)
cv2.imwrite('output.jpg', img)


[[  0   0   0 ... 127 127 127]
 [  0   0   0 ... 127 127 128]
 [  0   0   1 ... 127 128 128]
 ...
 [127 127 127 ... 254 254 255]
 [127 127 128 ... 254 255 255]
 [127 128 128 ... 255 255 255]]


True